spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@127.0.0.1:27017/test
  mvc:
    view:
      prefix: /templates/
      suffix: .html
    static-path-pattern: /**
  resources:
    static-locations:  classpath:/META-INF/resources/,classpath:/resources/,classpath:/,classpath:/public/,classpath:/itstyle/


